- name: reload daemon
  systemd:
    daemon_reload: yes

- name: reload firewalld
  systemd:
    name: firewalld
    state: restarted
    enabled: yes

- name: Reload service couchbase
  systemd:
    name: couchbase-server
    enabled: yes
