- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - haproxy
    - hacluster
    - corosync
    - pacemaker

- name: make virtual ip for haproxy
  ansible.builtin.shell: "pcs resource create blitz_virtual_ip ocf:heartbeat:IPaddr2 ip={{ virtual_ip }} cidr_netmask={{ netmask }} nic={{ interface }} op monitor interval=30s"
  tags: master

- name: edit haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

    #- name: add pem crt
    #  template:
    #    src: haproxy.pem.j2
    #    dest: /etc/haproxy/haproxy.cfg
