- name: install rsync
  yum:
    name: rsync

- name: Create a directory for ssh if it does not exist
  file:
    path: /usr/share/identityblitz/.ssh/
    state: directory
    owner: blitz
    mode: '0700'

- name: create file authorized_keys
  template:
    src: authorized_keys.j2
    dest: /usr/share/identityblitz/.ssh/authorized_keys
    mode: '0600'
    owner: blitz
    
    #- name: Change directory ownership
    #  file:
    #    path: /usr/share/identityblitz/.ssh
    #    owner: blitz
    #    group: blitz
    #    recurse: yes

    #- name: copy shell script to add pub key from master
    #  template:
    #    src: ssh_script.sh.j2
    #    dest: /usr/share/identityblitz/ssh_script.sh  #/tmp/ssh_script.sh
    #    mode: '0770'

    #- name: Change file ownership
    #  file:
    #    path: /usr/share/identityblitz/ssh_script.sh
    #    owner: blitz
    #    group: blitz

#- name: execute script
#  become_user: blitz
#  shell: /usr/share/identityblitz/ssh_script.sh
    #- name: Run a command as blitz
    #  command: /tmp/ssh_script.sh
    #  become: yes
    #  become_method: su
    #  become_user: blitz
