#- name: install nginx
#  yum:
#    name: epel-release
#    state: present

- name: install nginx
  yum:
    name: nginx
    state: present

- name: make directory for ssl crt
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: copy ssl crt
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{item.mode}}"
  with_items:
      - { src: 'dtp.eispd.ru.crt',dest: '/etc/nginx/ssl', mode: '0644'}
      - { src: 'dtp.eispd.ru.key',dest: '/etc/nginx/ssl', mode: '0600'}
      - { src: 'nginx.key',dest: '/etc/nginx/ssl', mode: '0644'}
      - { src: 'nginx.crt',dest: '/etc/nginx/ssl', mode: '0644'}
  notify: start nginx
  #- name: start nginx
  #    systemd:
  #    state: started
  #    name: nginx
  #    enabled: yes
